# Generated by Django 6.0.1 on 2026-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = soft-deleted (hidden from listings, kept for order history)'),
        ),
    ]
